### ISSUE TITLE
Add some gamified interface to make visualisation even more easier

### ISSUE THREAD

**Issue by itsrishibajpai** [devclub-biet-jhansi/binary-search-visualisation#1]
Requesting feature to create some kind of gamified interface to make Linear Search Visualisation even more easier for beginners.
Something that can be embedded in the same webpage, built using `HTML` , `CSS` , `JS` , `JQUERY`

**Comment by build-with-rishi** [comment]
I would like to work on this project and create a similar interface as i made for the Linear Search project repository.

**Comment by itsrishibajpai** [comment]
> I would like to work on this project and create a similar interface as i made for the Linear Search project repository.

Okay, here I am assigning you this issue and your request is being reviewed. 

Cheers!!
